(function(){
  var NO='1133260807';
  function d(){return window.ALALYLI_FIFO_DATA||window.ALALYLI_FIFO_PACK||null}
  function esc(x){return String(x==null?'':x).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function n(x){return String(x||'').toLocaleLowerCase('tr-TR').replace(/ı/g,'i').replace(/İ/g,'i').replace(/\s+/g,' ').trim()}
  function money(x,dec){if(x==null||x==='')return '—'; var v=+x; if(!isFinite(v))return esc(x); return v.toLocaleString('tr-TR',{minimumFractionDigits:dec==null?2:dec,maximumFractionDigits:dec==null?2:dec})}
  function pct(x){if(x==null||x==='')return '—';return '%'+money(x,2)}
  function kpi(t,v,cls){return '<div class="box '+(cls||'')+'"><small>'+esc(t)+'</small><b>'+v+'</b></div>'}
  function unpack(){var F=d(); if(!F)return null; if(F.summary)return F; var P=F.p||[],D=F.d||{},R=F.r||[],meta=F.m||{}; var summary=P; var moves={}; R.forEach(function(r){var p=P[r[0]]; if(!p)return; var key=p[0]; var row=[D.dt[r[1]],r[2]===0?'ALIŞ':'SATIŞ',D.c[r[3]],D.f[r[4]],r[5],r[6],r[7],r[8],r[9],r[10],r[11],r[12],r[13],r[14],r[15],D.s[r[16]],D.src[r[17]]]; (moves[key]||(moves[key]=[])).push(row)}); return {meta:{updateNo:meta.u,summaryCount:meta.p,moveCount:meta.r,source:meta.src},summary:summary,moves:moves}}
  function findSummary(F,key){return F&&F.summary.find(function(r){return r[0]===key})}
  function options(list,sel){return list.map(function(r){return '<option value="'+esc(r[0])+'" '+(r[0]===sel?'selected':'')+'>'+esc(r[1])+' — '+esc(r[3]||r[2]||'')+'</option>'}).join('')}
  function filteredProducts(F,q){q=n(q);return F.summary.filter(function(r){return !q||n(r[1]).indexOf(q)>=0||n(r[0]).indexOf(q)>=0||n(r[3]).indexOf(q)>=0||n(r[6]).indexOf(q)>=0||n(r[5]).indexOf(q)>=0}).slice(0,500)}
  function rowStatusClass(st){st=String(st||''); if(st.indexOf('EKSİK')>=0||st.indexOf('UYARI')>=0||st.indexOf('NEGAT')>=0)return 'bad'; if(st.indexOf('STOK DIŞI')>=0||st.indexOf('AÇILIŞ')>=0)return 'warn'; return ''}
  function moveTable(rows,type){var data=rows.filter(function(r){return !type||r[1]===type}); if(!data.length)return '<div class="tile">Bu bölümde hareket yok.</div>'; if(type==='ALIŞ')return '<div class="wrap"><table><thead><tr><th>Tarih</th><th>Tedarikçi</th><th>Fatura</th><th>Giriş Adet</th><th>Net Alış Hrç</th><th>Net Tutar Hrç</th><th>Hareket Sonrası Stok</th><th>Durum</th></tr></thead><tbody>'+data.map(function(r){return '<tr class="'+rowStatusClass(r[15])+'"><td>'+esc(r[0])+'</td><td>'+esc(r[2])+'</td><td>'+esc(r[3])+'</td><td>'+money(r[4],2)+'</td><td>'+money(r[6],4)+'</td><td>'+money(r[9],2)+'</td><td>'+money(r[14],2)+'</td><td>'+esc(r[15])+'</td></tr>'}).join('')+'</tbody></table></div>'; if(type==='SATIŞ')return '<div class="wrap"><table><thead><tr><th>Tarih</th><th>Müşteri</th><th>Satış Fatura</th><th>Satış Adet</th><th>Satış Birim Hrç</th><th>FIFO Birim</th><th>FIFO Toplam</th><th>Adet Kâr</th><th>Toplam Kâr</th><th>Marj</th><th>Oran</th><th>Satış Sonrası Stok</th><th>FIFO Kaynak</th><th>Durum</th></tr></thead><tbody>'+data.map(function(r){var oran=(+r[10])?(+r[12])/(+r[10])*100:null;return '<tr class="'+rowStatusClass(r[15])+'"><td>'+esc(r[0])+'</td><td>'+esc(r[2])+'</td><td>'+esc(r[3])+'</td><td>'+money(r[5],2)+'</td><td>'+money(r[7],4)+'</td><td>'+money(r[8],4)+'</td><td>'+money(r[10],2)+'</td><td>'+money(r[11],4)+'</td><td><b>'+money(r[12],2)+'</b></td><td>'+pct(r[13])+'</td><td>'+pct(oran)+'</td><td>'+money(r[14],2)+'</td><td>'+esc(r[16])+'</td><td>'+esc(r[15])+'</td></tr>'}).join('')+'</tbody></table></div>'; return '<div class="wrap"><table><thead><tr><th>Tarih</th><th>Hareket</th><th>Cari/Tedarikçi</th><th>Fatura</th><th>Giriş</th><th>Çıkış</th><th>Alış Birim</th><th>Satış Birim</th><th>FIFO Birim</th><th>Net Tutar</th><th>FIFO Toplam</th><th>Kâr</th><th>Marj</th><th>Stok</th><th>Durum</th></tr></thead><tbody>'+data.map(function(r){return '<tr class="'+rowStatusClass(r[15])+'"><td>'+esc(r[0])+'</td><td>'+esc(r[1])+'</td><td>'+esc(r[2])+'</td><td>'+esc(r[3])+'</td><td>'+money(r[4],2)+'</td><td>'+money(r[5],2)+'</td><td>'+money(r[6],4)+'</td><td>'+money(r[7],4)+'</td><td>'+money(r[8],4)+'</td><td>'+money(r[9],2)+'</td><td>'+money(r[10],2)+'</td><td>'+money(r[12],2)+'</td><td>'+pct(r[13])+'</td><td>'+money(r[14],2)+'</td><td>'+esc(r[15])+'</td></tr>'}).join('')+'</tbody></table></div>'}
  var cache=null; function F(){return cache||(cache=unpack())}
  function renderDetail(){var FF=F(); if(!FF)return; var sel=document.getElementById('fifoProduct'); if(!sel)return; var key=sel.value; var s=findSummary(FF,key); if(!s)return; var rows=(FF.moves&&FF.moves[key])||[]; var body=document.getElementById('fifoBody'); if(!body)return; body.innerHTML='<div class="mini">'+kpi('Ürün',esc(s[1]))+kpi('Sınıf / Kategori',esc((s[2]||'')+' / '+(s[3]||'')))+kpi('Toplam Alış Adet',money(s[7],2),'alis')+kpi('Toplam Satış Adet',money(s[8],2),'satis')+kpi('Kalan Stok',money(s[9],2),s[9]<0?'bad':'')+kpi('Eksik/Açılış Adet',money(s[10],2),s[10]>0?'warn':'')+kpi('Alış Net Hrç',money(s[11],2)+' TL','alis')+kpi('Satış Net Hrç',money(s[12],2)+' TL','satis')+kpi('FIFO Maliyet',money(s[13],2)+' TL')+kpi('Toplam Kâr',money(s[14],2)+' TL',s[14]<0?'bad':'good')+kpi('Marj / Oran',pct(s[15])+' / '+pct(s[16]))+kpi('Hareket Sayısı',rows.length)+'</div><div class="grid"><div class="tile"><h3>Stok/FIFO Kontrol</h3><div class="line"><span>Alış satır</span><b>'+money(s[17],0)+'</b></div><div class="line"><span>Satış satır</span><b>'+money(s[18],0)+'</b></div><div class="line"><span>Barkod/Kod</span><b>'+esc((s[5]||'')+' '+(s[6]||''))+'</b></div><div class="line"><span>Kontrol sonucu</span><b>'+(s[10]>0?'Açılış/eksik alış var':'FIFO stok zinciri kuruldu')+'</b></div></div><div class="tile"><h3>Hesap Kuralı</h3><div class="line"><span>Kâr</span><b>Satış Hrç - FIFO</b></div><div class="line"><span>Marj</span><b>Kâr / Satış Hrç</b></div><div class="line"><span>Oran</span><b>Kâr / FIFO</b></div><div class="line"><span>Stok</span><b>Her hareket sonrası</b></div></div></div><h3>Alış Hareketleri</h3>'+moveTable(rows,'ALIŞ')+'<h3>Satış Hareketleri / FIFO Kâr</h3>'+moveTable(rows,'SATIŞ')+'<h3>Tüm Hareket Zaman Çizelgesi</h3>'+moveTable(rows)}
  function refreshOptions(){var FF=F(); if(!FF)return; var q=document.getElementById('fifoSearch')?document.getElementById('fifoSearch').value:'';var list=filteredProducts(FF,q);var sel=document.getElementById('fifoProduct');if(!sel)return;var old=sel.value;sel.innerHTML=options(list, list.some(function(r){return r[0]===old})?old:(list[0]&&list[0][0]));renderDetail()}
  function install(){var FF=F(); var sec=document.getElementById('urun'); if(!sec)return false; var old=document.getElementById('fifoProductCard'); if(old)old.remove(); if(!FF){sec.insertAdjacentHTML('afterbegin','<div class="card" id="fifoProductCard"><div class="head"><h3>Ürün FIFO Hareket Kartı</h3><div class="muted">Veri dosyası bekleniyor. Aşama 1: ekran motoru hazır.</div></div></div>'); return false} var def=(FF.summary.find(function(r){return String(r[0]).indexOf('MOLY_60X90')>=0})||FF.summary[0]||[])[0]; sec.insertAdjacentHTML('afterbegin','<div class="card" id="fifoProductCard"><div class="head"><h3>Ürün FIFO Hareket Kartı — Canlı Dashboard</h3><div class="muted">Excel yok. ALIŞ RAPORU (5) + SATIŞ RAPORU (24) dashboard içine işlendi. Her ürün için alış, satış, FIFO maliyet, stok, kâr, marj ve oran burada.</div></div><div class="mini"><div class="box"><small>Ürün Ara</small><input id="fifoSearch" placeholder="Ürün, barkod, kod, kategori yaz" style="width:100%;padding:10px;border-radius:8px;border:1px solid #b8cce5;font-weight:900"></div><div class="box"><small>Ürün Seç</small><select id="fifoProduct" style="width:100%;padding:10px;border-radius:8px;font-weight:900"></select></div><div class="box"><small>Kapsam</small><b>'+esc(FF.meta.summaryCount)+' ürün / '+esc(FF.meta.moveCount)+' hareket</b></div><div class="box"><small>Güncelleme No</small><b>'+esc(FF.meta.updateNo)+'</b></div></div><div id="fifoBody" style="padding:0 12px 12px"></div></div>'); document.getElementById('fifoSearch').oninput=refreshOptions; document.getElementById('fifoProduct').onchange=renderDetail; refreshOptions(); if(def){document.getElementById('fifoProduct').value=def;renderDetail()} return true}
  function tryInstall(){var st=document.getElementById('stamp'); if(st)st.textContent='Güncelleme No: '+NO; install()}
  setTimeout(tryInstall,0);setTimeout(tryInstall,500);setTimeout(tryInstall,1500);setTimeout(tryInstall,3000); window.ALALYLI_FIFO_RENDER=tryInstall;
})();