(function(){
var NO='1540261707';
function n(x){return String(x||'').toLocaleLowerCase('tr-TR').replace(/ı/g,'i').replace(/İ/g,'i').replace(/\s+/g,' ').trim()}
function esc(x){return String(x==null?'':x).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function money(x,d){return(+x||0).toLocaleString('tr-TR',{minimumFractionDigits:d==null?2:d,maximumFractionDigits:d==null?2:d})}
function vat(p){var s=n(p&&p[1]);return s.includes('çinko')||s.includes('cinko')?1.20:1.10}
function netProfit(o){return(+o[7]||0)-(+o[9]||0)-(+o[10]||0)}
function pct(a,b){return b?(a/b*100):0}
function orderDate(o){var t=String(o&&o[1]||'').replace(/\s*\/\s*Fatura:\s*[0-9.]+.*$/,'');return t||'—'}
function invDate(o){var m=String(o&&o[1]||'').match(/Fatura:\s*([0-9.]+)/);return m?m[1]:'—'}
function load(src,cb){var base=src.split('?')[0];if(document.querySelector('script[src^="'+base+'"]')){cb&&cb();return}var s=document.createElement('script');s.src=src;s.onload=function(){cb&&cb()};s.onerror=function(){console.warn('Yüklenemedi:',src);cb&&cb()};document.head.appendChild(s)}
function feyzaOrder(){return ['FEYZA MEDİKAL / BURSA','17.07.2026','FATURA BEKLİYOR','SEVK EDİLMEDİ','Mayıs 2026','Jender %12,59 / Moly %13,05','Bursa',6654.55,7320.00,4167.29,0,2487.26]}
function feyzaProducts(){return [['FEYZA','Jender serme 60x90',24,'Mayıs 2026','12,59%',102.3871,'30.12.2025','IST2025000001640','Fatura içi iskonto / serme %5 uygulanmaz',170.00,3709.09,1251.80],['FEYZA','Moly serme 60x90',24,'Mayıs 2026','13,05%',71.25,'30.11.2025','IST2025000001583','Uygulanmaz / serme %5 uygulanmaz',135.00,2945.46,1235.46]]}
function applyFeyza(){var d=window.HASTA_BEZI_DATA;if(!d)return;d.orders=(d.orders||[]).filter(function(o){return String(o&&o[0]||'').indexOf('FEYZA MEDİKAL')<0}).concat([feyzaOrder()]);d.products=(d.products||[]).filter(function(p){return String(p&&p[0]||'')!=='FEYZA'}).concat(feyzaProducts());d.checks=(d.checks||[]).filter(function(c){return String(c&&c[0]||'')!=='FEYZA-170726'}).concat([['FEYZA-170726','FATURA BEKLİYOR','AÇIK','7.320,00','Feyza Medikal Bursa: Jender 60x90 serme 4 balya 170 TL KDV dahil; Moly 60x90 serme 4 balya 135 TL KDV dahil. Nakliye girilmedi: 0 / bekliyor.']]);if(window.HASTA_BEZI_GORUKLE_ILAVE)window.HASTA_BEZI_GORUKLE_ILAVE.updateNo=NO;}
function keyOf(o){var s=String(o&&o[0]||'').toUpperCase();if(s.includes('FEYZA'))return'FEYZA';if(s.includes('GÖRÜKLE'))return'GÖRÜKLE';if(s.includes('ZEYBEK'))return'ZEYBEK';if(s.includes('SERCAN'))return'SERCAN';if(s.includes('SETON'))return'SETON';return s.split(' ')[0]}
function allOrders(){var d=window.HASTA_BEZI_DATA||{},g=window.HASTA_BEZI_GORUKLE_ILAVE||{};var orders=(d.orders||[]).slice();if(g.replaceOrderName&&g.order)orders=orders.filter(function(o){return o[0]!==g.replaceOrderName}).concat([g.order]);return orders}
function allProducts(){var d=window.HASTA_BEZI_DATA||{},g=window.HASTA_BEZI_GORUKLE_ILAVE||{};var products=(d.products||[]).slice();if(g.replaceProductsFor&&g.products)products=products.filter(function(p){return p[0]!==g.replaceProductsFor}).concat(g.products);return products}
function dhl(v,d){return '<b style="display:block;background:#fff3b0;border:1px solid #d6b900;padding:4px 7px;border-radius:6px;font-size:14px;color:#06142a">'+money(v,d==null?4:d)+'</b>'}
function packInfo(p){var q=+p[2]||0,s=n(p[1]);if((s.includes('serme')||s.includes('yatak koruyucu')||s.includes('60x90')||s.includes('90x180'))&&q%6===0)return (q/6)+' balya / '+q+' paket';return q+' paket/adet'}
function productDetail(p){var q=+p[2]||0,vr=vat(p),birimDhl=+p[9]||0,birimHrc=birimDhl/vr,sat=+p[10]||0,kdv=sat*(vr-1),gross=sat*vr,costUnit=+p[5]||0,cost=costUnit*q,kar=+p[11]||0;return '<tr><td>'+esc(p[1])+'</td><td>'+esc(packInfo(p))+'</td><td>'+dhl(birimDhl,2)+'</td><td>'+money(birimHrc,4)+'</td><td>'+money(sat)+'</td><td>'+money(kdv)+'</td><td>'+money(gross)+'</td><td>'+money(costUnit,4)+'</td><td>'+money(cost)+'</td><td>'+money(kar)+'</td><td>%'+money(pct(kar,sat))+' / %'+money(pct(kar,cost))+'</td><td>'+esc(p[6])+'</td><td>'+esc(p[7])+'</td><td>'+esc(p[8])+'</td><td>'+esc(p[3])+'</td><td>'+esc(p[4]==='Yok'?'0 / Yok':p[4])+'</td></tr>'}
function invoiceDetail(o){var ps=allProducts().filter(function(p){return p[0]===keyOf(o)});var k=netProfit(o),open=String(o[2]||'').includes('BEKLİYOR')||String(o[3]||'').includes('BEKLİYOR')||String(o[3]||'').includes('EDİLMEDİ');return '<div class="classic-info" style="margin-top:14px;background:#fff;border:1px solid #c8d9ec;border-radius:12px;padding:12px;color:#06142a"><h3 style="margin:0 0 10px;color:#06142a">Fatura Kesim Detayı — Eksiksiz Bilgi</h3><div class="mini"><div class="box"><small>Cari</small><b>'+esc(o[0])+'</b></div><div class="box"><small>İşlem Tarihi</small><b>'+esc(orderDate(o))+'</b></div><div class="box"><small>Fatura No</small><b>'+esc(o[2]||'—')+'</b></div><div class="box"><small>Fatura Tarihi</small><b>'+esc(invDate(o))+'</b></div><div class="box"><small>Sevk Durumu</small><b>'+esc(o[3]||'—')+'</b></div><div class="box"><small>Sipariş Kapanışı</small><b>'+(open?'AÇIK — fatura/sevk bekliyor':'KAPALI')+'</b></div><div class="box"><small>Kaynak Liste</small><b>'+esc(o[4]||'—')+'</b></div><div class="box"><small>İskonto Notu</small><b>'+esc(o[5]||'0')+'</b></div><div class="box"><small>Rota</small><b>'+esc(o[6]||'—')+'</b></div></div><div class="wrap" style="margin-top:12px;max-height:none"><table><thead><tr><th>Ürün</th><th>Miktar</th><th>Birim KDV Dahil</th><th>Birim KDV Hariç</th><th>Satış Hrç</th><th>KDV</th><th>KDV Dahil</th><th>FIFO Birim</th><th>FIFO Toplam</th><th>Kâr</th><th>Marj / Oran</th><th>Alış Tarihi</th><th>Alış Fatura</th><th>Fark Fatura</th><th>Liste</th><th>İskonto</th></tr></thead><tbody>'+ps.map(productDetail).join('')+'</tbody></table></div><div class="mini" style="margin-top:12px"><div class="box"><small>Satış KDV Hariç</small><b>'+money(o[7])+' TL</b></div><div class="box"><small>KDV Dahil</small><b>'+money(o[8])+' TL</b></div><div class="box"><small>FIFO Maliyet</small><b>'+money(o[9])+' TL</b></div><div class="box"><small>Nakliye</small><b>'+money(o[10])+' TL</b></div><div class="box"><small>Net Kâr</small><b>'+money(k)+' TL</b></div><div class="box"><small>Kâr Marjı / Oranı</small><b>%'+money(pct(k,o[7]))+' / %'+money(pct(k,o[9]))+'</b></div></div><div style="margin-top:10px;font-weight:900;color:#806000">Kural: Kâr KDV hariç hesaplanır. Kâr Oranı = Kâr / FIFO Maliyet. Nakliye paydasına eklenmez. Serme ürünlerinde Kar-Dağ %5 uygulanmaz.</div></div>'}
function card(o,prefix,i){var k=netProfit(o),open=String(o[2]||'').includes('BEKLİYOR')||String(o[3]||'').includes('BEKLİYOR')||String(o[3]||'').includes('EDİLMEDİ'),id=prefix+i;return '<div class="card click" onclick="var x=document.getElementById(\''+id+'\');if(x)x.classList.toggle(\'open\')"><div class="head"><h3>'+esc(o[0])+' '+(open?'<span class="pill pwarn">AÇIK</span>':'<span class="pill pgood">KAPALI</span>')+'</h3><div class="muted"><b>İşlem Tarihi:</b> '+esc(orderDate(o))+' | Fatura: '+esc(o[2]||'—')+' | Sevk: '+esc(o[3]||'—')+'</div></div><div class="detail" id="'+id+'"><div class="mini"><div class="box"><small>İşlem Tarihi</small><b>'+esc(orderDate(o))+'</b></div><div class="box"><small>Satış Hrç</small><b>'+money(o[7])+' TL</b></div><div class="box"><small>KDV Dahil</small><b>'+money(o[8])+' TL</b></div><div class="box"><small>FIFO</small><b>'+money(o[9])+' TL</b></div><div class="box"><small>Nakliye</small><b>'+money(o[10])+' TL</b></div><div class="box"><small>Net Kâr</small><b>'+money(k)+' TL</b></div><div class="box"><small>Marj / Oran</small><b>%'+money(pct(k,o[7]))+' / %'+money(pct(k,o[9]))+'</b></div></div>'+invoiceDetail(o)+'</div></div>'}
function patchKpis(orders){var k=document.getElementById('kpis');if(!k)return;var h=orders.reduce(function(s,o){return s+(+o[7]||0)},0),d=orders.reduce(function(s,o){return s+(+o[8]||0)},0),f=orders.reduce(function(s,o){return s+(+o[9]||0)},0),nak=orders.reduce(function(s,o){return s+(+o[10]||0)},0),kar=orders.reduce(function(s,o){return s+netProfit(o)},0);k.innerHTML=[['Açık Cari',orders.length],['Satış Hrç',money(h)+' TL'],['KDV Dahil',money(d)+' TL'],['FIFO',money(f)+' TL'],['Nakliye',money(nak)+' TL'],['Net Kâr',money(kar)+' TL'],['Marj','%'+money(pct(kar,h))],['Oran','%'+money(pct(kar,f))]].map(function(x){return '<div class="kpi"><small>'+x[0]+'</small><b>'+x[1]+'</b></div>'}).join('')}
function patchOrders(){var orders=allOrders();patchKpis(orders);var cards=document.getElementById('cards');if(cards)cards.innerHTML=orders.map(function(o,i){return card(o,'c',i)}).join('');var ord=document.getElementById('orders');if(ord)ord.innerHTML=orders.map(function(o,i){return card(o,'o',i)}).join('');var sh=document.getElementById('shipments');if(sh)sh.innerHTML='<div class="card"><div class="head"><h3>Sevkiyat Kontrolü</h3></div><div class="wrap"><table><thead><tr><th>İşlem Tarihi</th><th>Cari</th><th>Fatura</th><th>Sevkiyat</th><th>Rota</th><th>Nakliye</th><th>Durum</th></tr></thead><tbody>'+orders.map(function(o){var wait=String(o[3]).includes('BEKLİYOR')||String(o[3]).includes('EDİLMEDİ');return '<tr><td>'+esc(orderDate(o))+'</td><td>'+esc(o[0])+'</td><td>'+esc(o[2])+'</td><td>'+esc(o[3])+'</td><td>'+esc(o[6])+'</td><td>'+money(o[10])+'</td><td class="'+(wait?'warn':'good')+'">'+(wait?'BEKLİYOR':'TAMAM')+'</td></tr>'}).join('')+'</tbody></table></div></div>'}
function patchProducts(){var t=document.getElementById('products');if(!t)return;var products=allProducts();t.innerHTML='<thead><tr><th>Cari</th><th>Ürün</th><th>Adet</th><th>Liste</th><th>İskonto</th><th>Birim Maliyet</th><th>Alış Tarih</th><th>Alış Fatura</th><th>Fark Fatura</th><th>İsk.Dhl</th><th>Satış Hrç</th><th>Net Satış Dhl</th><th>Kâr</th><th>Marj %</th><th>Oran %</th></tr></thead><tbody>'+products.map(function(p){var cost=(+p[5]||0)*(+p[2]||0),kar=+p[11]||0,sat=+p[10]||0;return '<tr><td>'+esc(p[0])+'</td><td>'+esc(p[1])+'</td><td>'+esc(p[2])+'</td><td>'+esc(p[3])+'</td><td>'+esc(p[4])+'</td><td>'+money(p[5],4)+'</td><td>'+esc(p[6])+'</td><td>'+esc(p[7])+'</td><td>'+esc(p[8])+'</td><td>'+dhl(p[9],4)+'</td><td>'+money(sat)+'</td><td>'+dhl(sat*vat(p),2)+'</td><td>'+money(kar)+'</td><td>'+money(pct(kar,sat))+'</td><td>'+money(pct(kar,cost))+'</td></tr>'}).join('')+'</tbody>'}
function patchChecks(){var d=window.HASTA_BEZI_DATA||{},t=document.getElementById('checks');if(!t)return;t.innerHTML='<thead><tr><th>Alış Fatura</th><th>Fark Fatura</th><th>Durum</th><th>Tutar</th><th>Not</th></tr></thead><tbody>'+(d.checks||[]).map(function(c){return '<tr><td>'+esc(c[0])+'</td><td>'+esc(c[1])+'</td><td class="'+(String(c[2]).includes('KESİLDİ')?'good':'warn')+'">'+esc(c[2])+'</td><td>'+esc(c[3])+'</td><td>'+esc(c[4])+'</td></tr>'}).join('')+'</tbody>'}
function run(){applyFeyza();patchOrders();patchProducts();patchChecks();var st=document.getElementById('stamp');if(st)st.textContent='🆚 '+NO;if(window.ALALYLI_VERSION_BADGE)window.ALALYLI_VERSION_BADGE();if(window.ALALYLI_MASTER_GUARD)window.ALALYLI_MASTER_GUARD();}
function boot(){run();load('./version_badge_patch.js?v='+NO,function(){run()});load('./master_guard_patch.js?v='+NO,function(){run()});load('./price_compare_data.js?v='+NO,function(){load('./price_compare.js?v='+NO,function(){if(window.ALALYLI_PRICE_RENDER)window.ALALYLI_PRICE_RENDER();run()})});if(window.ALALYLI_FIFO_RENDER)window.ALALYLI_FIFO_RENDER();}
[0,100,500,1200,2500,5000].forEach(function(t){setTimeout(boot,t)});
})();