(function(){
var NO='1137260807';
function n(x){return String(x||'').toLocaleLowerCase('tr-TR').replace(/ı/g,'i').replace(/İ/g,'i').replace(/\s+/g,' ').trim()}
function money(x,d){return(+x||0).toLocaleString('tr-TR',{minimumFractionDigits:d==null?2:d,maximumFractionDigits:d==null?2:d})}
function load(src,cb){var base=src.split('?')[0];if(document.querySelector('script[src^="'+base+'"]')){cb&&cb();return}var s=document.createElement('script');s.src=src;s.onload=function(){cb&&cb()};s.onerror=function(){console.warn('Yüklenemedi:',src);cb&&cb()};document.head.appendChild(s)}
function keyName(x){var s=n(x);if(s.includes('moly')&&(s.includes('serme')||s.includes('60x90')||s.includes('yatak koruyucu')||s.includes('örtü')||s.includes('ortu')))return'MOLY_60X90';if(s.includes('jender')&&(s.includes('bel bantlı')||s.includes('bel bantli')||s.includes('bağlama')||s.includes('baglama')))return'JENDER_BAGLAMA';if(s.includes('serme')||s.includes('yatak koruyucu')||s.includes('örtü')||s.includes('ortu'))return'SERME_YATAK_KORUYUCU';return s.toUpperCase()}
function forceMoly(){document.querySelectorAll('table').forEach(function(t){var th=[].slice.call(t.querySelectorAll('thead th')),labels=th.map(function(x){return x.textContent.trim()}),u=labels.indexOf('Ürün'),list=labels.indexOf('Liste'),lh=labels.indexOf('Liste Hrç'),ld=labels.indexOf('Liste Dhl'),isk=labels.indexOf('İsk.Dhl'),s=labels.indexOf('Satış Hrç'),nd=labels.indexOf('Net Satış Dhl'),k=labels.indexOf('Kâr'),mj=labels.indexOf('Marj %'),or=labels.indexOf('Oran %'),adet=labels.indexOf('Adet');if(u<0)return;[].slice.call(t.querySelectorAll('tbody tr')).forEach(function(r){var c=[].slice.call(r.children),name=c[u]&&c[u].textContent,ln=list>=0&&c[list]?c[list].textContent:'';if(keyName(name)!=='MOLY_60X90'||!n(ln).includes('nisan'))return;var q=adet>=0&&c[adet]?parseFloat(c[adet].textContent.replace(',','.'))||60:60,hrc=115.59,dhl=127.149,sat=hrc*q,netd=sat*1.10,cost=71.25*q,kar=sat-cost;if(lh>=0&&c[lh])c[lh].textContent=money(hrc,4);if(ld>=0&&c[ld])c[ld].innerHTML='<b style="display:block;background:#fff3b0;border:1px solid #d6b900;padding:4px 7px;border-radius:6px;font-size:14px">'+money(dhl,4)+'</b>';if(isk>=0&&c[isk])c[isk].innerHTML='<b style="display:block;background:#fff3b0;border:1px solid #d6b900;padding:4px 7px;border-radius:6px;font-size:14px">'+money(dhl,4)+'</b>';if(s>=0&&c[s])c[s].textContent=money(sat,2);if(nd>=0&&c[nd])c[nd].innerHTML='<b style="display:block;background:#fff3b0;border:1px solid #d6b900;padding:4px 7px;border-radius:6px;font-size:14px">'+money(netd,2)+'</b>';if(k>=0&&c[k])c[k].textContent=money(kar,2);if(mj>=0&&c[mj])c[mj].textContent=money(kar/sat*100,2);if(or>=0&&c[or])c[or].textContent=money(kar/cost*100,2);})})}
function boot(){var st=document.getElementById('stamp');if(st)st.textContent='Güncelleme No: '+NO;forceMoly();load('./price_compare_data.js?v='+NO,function(){load('./price_compare.js?v='+NO,function(){if(window.ALALYLI_PRICE_RENDER)window.ALALYLI_PRICE_RENDER()})});load('./fifo_pack.js?v='+NO,function(){load('./fifo_dashboard.js?v='+NO,function(){if(window.ALALYLI_FIFO_RENDER)window.ALALYLI_FIFO_RENDER()})});load('./fifo_dashboard.js?v='+NO,function(){if(window.ALALYLI_FIFO_RENDER)window.ALALYLI_FIFO_RENDER()})}
setTimeout(boot,0);setTimeout(boot,700);setTimeout(function(){forceMoly();if(window.ALALYLI_FIFO_RENDER)window.ALALYLI_FIFO_RENDER();if(window.ALALYLI_PRICE_RENDER)window.ALALYLI_PRICE_RENDER()},2000);setTimeout(forceMoly,5000);try{new MutationObserver(function(){setTimeout(forceMoly,50)}).observe(document.body,{childList:true,subtree:true})}catch(e){}
})();