(function(){
  var NO='1540261707';
  function esc(x){return String(x==null?'':x).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function load(src,cb){var base=src.split('?')[0];if(document.querySelector('script[src^="'+base+'"]')){cb&&cb();return}var s=document.createElement('script');s.src=src;s.onload=function(){cb&&cb()};s.onerror=function(){console.warn('Yüklenemedi:',src);cb&&cb()};document.head.appendChild(s)}
  function show(id,title){document.querySelectorAll('.nav').forEach(function(b){b.classList.toggle('active',b.dataset.s===id)});document.querySelectorAll('.section').forEach(function(s){s.classList.toggle('active',s.id===id)});var t=document.getElementById('title');if(t)t.textContent=title||document.querySelector('[data-s="'+id+'"]')?.textContent||id}
  function ensureNav(id,label,beforeId){var side=document.querySelector('.side');if(!side)return null;var b=document.querySelector('[data-s="'+id+'"]');if(!b){b=document.createElement('button');b.className='nav';b.dataset.s=id;b.textContent=label;b.onclick=function(){show(id,label)};}var before=beforeId?document.querySelector('[data-s="'+beforeId+'"]'):null;if(before&&before.parentNode===side)side.insertBefore(b,before);else if(!b.parentNode)side.appendChild(b);return b}
  function reorderNav(){var side=document.querySelector('.side');if(!side)return;ensureNav('hastabezirapor','Hasta Bezi Rapor','kardag');var order=['ana','siparis','sevkiyat','urun','arama','hastabezirapor','listefiyat','kardag','kontrol'];order.forEach(function(id){var b=document.querySelector('[data-s="'+id+'"]');if(b)side.appendChild(b)});}
  function ensureReport(){var main=document.querySelector('.main');if(!main)return;var sec=document.getElementById('hastabezirapor');if(!sec){sec=document.createElement('section');sec.id='hastabezirapor';sec.className='section';main.appendChild(sec);}sec.innerHTML='<div class="card"><div class="head"><h3>Hasta Bezi Rapor</h3><div class="muted">Bu ekran tam satış/FIFO veri paketi canlıya bağlanınca otomatik dolacak. Şimdilik iskelet ve kontrol hazır; veri eksikse tamamlandı sayılmaz.</div></div><div class="wrap"><table><thead><tr><th>Kırılım</th><th>Kanal</th><th>Bugün TL</th><th>Dün TL</th><th>Bu Hafta TL</th><th>Bu Ay TL</th><th>Bir Önceki Ay TL</th><th>Bu Yıl TL</th><th>Önceki Yıl TL</th><th>Durum</th></tr></thead><tbody>'+['Belbantlı','Külotlu','Serme / Yatak Koruyucu','Mesane'].map(function(k){return ['Perakende','Distribütör-Toptan'].map(function(c){return '<tr><td>'+k+'</td><td>'+c+'</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td class="warn">Tam satış/FIFO veri paketi bekliyor</td></tr>'}).join('')}).join('')+'</tbody></table></div></div>'}
  function dataStatus(){var fifo=window.ALALYLI_FIFO_PACK||window.ALALYLI_FIFO_DATA;var price=window.ALALYLI_PRICE_COMPARE;var rows=fifo&&(fifo.r||fifo.moves)?(fifo.r?fifo.r.length:Object.values(fifo.moves||{}).reduce(function(a,b){return a+b.length},0)):0;return {fifo:!!fifo,rows:rows,price:!!price,priceRows:price&&price.rows?price.rows.length:0}}
  function ensureControl(){var sec=document.getElementById('kontrol');if(!sec)return;var old=document.getElementById('masterControlCard');if(old)old.remove();var st=dataStatus();var html='<div class="tile" id="masterControlCard"><h3>Canlı Veri Bağlantı Kontrolü</h3><div class="line"><span>🆚 Format</span><b>HHMMYYDDMM / OK</b></div><div class="line"><span>Liste Fiyatları</span><b>'+(st.price?'CANLI — '+st.priceRows+' satır':'BEKLİYOR')+'</b></div><div class="line"><span>Tüm satış/FIFO veri paketi</span><b>'+(st.fifo?'CANLI — '+st.rows+' hareket':'BAĞLANMADI')+'</b></div><div class="line"><span>Tamamlandı mı?</span><b>'+(st.fifo?'EVET, ekranda doğrula':'HAYIR — satışlar canlıya bağlanmadan tamamlandı denmez')+'</b></div><div class="line"><span>Koruma</span><b>Sil/değiştir komutu olmadan eski işler korunur</b></div></div>';var grid=sec.querySelector('.grid');if(grid)grid.insertAdjacentHTML('afterbegin',html);else sec.insertAdjacentHTML('afterbegin','<div class="grid">'+html+'</div>')}
  function patchCards(){document.querySelectorAll('.click').forEach(function(card){if(card.dataset.masterLinked)return;var h=card.querySelector('h3');if(!h)return;card.dataset.masterLinked='1';card.title='Tıkla: cari detayını açar. Tam cari arama bağlantısı ayrıca tamamlanacak.'})}
  function apply(){reorderNav();ensureReport();ensureControl();patchCards();if(window.ALALYLI_LAST_SHIPMENT)window.ALALYLI_LAST_SHIPMENT();if(window.ALALYLI_VERSION_BADGE)window.ALALYLI_VERSION_BADGE();else document.querySelectorAll('#stamp,.stamp').forEach(function(el){el.textContent='🆚 '+NO})}
  load('./last_shipment_patch.js?v='+NO,function(){if(window.ALALYLI_LAST_SHIPMENT)window.ALALYLI_LAST_SHIPMENT()});
  [0,500,1500,3000,6000].forEach(function(t){setTimeout(apply,t)});window.ALALYLI_MASTER_GUARD=apply;
})();