(function(){
  var NO='1139260807';
  function raw(){return window.ALALYLI_PRICE_COMPARE||{rows:[],fields:[]}}
  function esc(x){return String(x==null?'':x).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function n(x){return String(x||'').toLocaleLowerCase('tr-TR').replace(/ı/g,'i').replace(/İ/g,'i').replace(/\s+/g,' ').trim()}
  function money(x,d){if(x==null||x==='')return '—';var v=+x;if(!isFinite(v))return esc(x);return v.toLocaleString('tr-TR',{minimumFractionDigits:d==null?2:d,maximumFractionDigits:d==null?2:d})}
  function pct(x){return x==null?'—':'%'+money(x,2)}
  function rowObj(r,fields){if(!Array.isArray(r))return r;var o={};fields.forEach(function(f,i){o[f]=r[i]});return o}
  function rows(){var D=raw(),fs=D.fields||[];return (D.rows||[]).map(function(r){return rowObj(r,fs)})}
  function trendClass(p){if(p==null)return '';if(p<0)return 'bad';if(p>=20)return 'bad';if(p>=10)return 'warn';return 'good'}
  function addNav(){if(document.querySelector('[data-s="listefiyat"]'))return;var side=document.querySelector('.side');if(!side)return;var b=document.createElement('button');b.className='nav';b.dataset.s='listefiyat';b.textContent='Liste Fiyatları';b.onclick=function(){show('listefiyat')};var ref=document.querySelector('[data-s="kontrol"]');side.insertBefore(b,ref||null);var main=document.querySelector('.main');var sec=document.createElement('section');sec.id='listefiyat';sec.className='section';sec.innerHTML='<div class="card" id="priceCard"><div class="head"><h3>Ürün Liste Fiyatları — Yan Yana Karşılaştırma</h3><div class="muted">Ekim, Ocak, Şubat, Nisan ve Mayıs liste fiyatları yan yana. Artış oranları KDV hariç paket net fiyat üzerinden hesaplanır.</div></div><div style="padding:12px"><div class="mini"><div class="box"><small>Ürün Ara</small><input id="priceSearch" placeholder="Ürün, barkod, kod yaz" style="width:100%;padding:10px;border-radius:8px;border:1px solid #b8cce5;font-weight:900"></div><div class="box"><small>Filtre</small><select id="priceFilter" style="width:100%;padding:10px;border-radius:8px;font-weight:900"><option value="all">Tüm ürünler</option><option value="mayis15">Nisan→Mayıs %15 üstü</option><option value="total30">Ekim→Mayıs %30 üstü</option><option value="negative">Düşen fiyatlar</option><option value="missing">Eksik listede olan</option></select></div><div class="box"><small>Kaynak</small><b id="priceSource">—</b></div><div class="box"><small>Kayıt</small><b id="priceCount">—</b></div></div><div id="priceBody"></div></div></div>';main.appendChild(sec);document.getElementById('priceSearch').oninput=render;document.getElementById('priceFilter').onchange=render}
  function show(id){document.querySelectorAll('.nav').forEach(function(b){b.classList.toggle('active',b.dataset.s===id)});document.querySelectorAll('.section').forEach(function(s){s.classList.toggle('active',s.id===id)});var t=document.getElementById('title');if(t)t.textContent='Liste Fiyatları'}
  function render(){var D=raw(),q=n(document.getElementById('priceSearch')&&document.getElementById('priceSearch').value),f=document.getElementById('priceFilter')&&document.getElementById('priceFilter').value||'all';var list=rows().filter(function(r){var ok=!q||n([r.name,r.barcode,r.code].join(' ')).indexOf(q)>=0;if(!ok)return false;if(f==='mayis15')return (r.pct_nisan_mayis||0)>=15;if(f==='total30')return (r.pct_ekim_mayis||0)>=30;if(f==='negative')return (r.pct_ekim_ocak<0)||(r.pct_ocak_subat<0)||(r.pct_subat_nisan<0)||(r.pct_nisan_mayis<0);if(f==='missing')return String(r.status||'')!=='OK';return true});var src=document.getElementById('priceSource'),cnt=document.getElementById('priceCount');if(src)src.textContent=D.source||'—';if(cnt)cnt.textContent=list.length+' / '+rows().length;var body=document.getElementById('priceBody');if(!body)return;body.innerHTML='<div class="wrap" style="max-height:72vh"><table><thead><tr><th>Ürün</th><th>Kod</th><th>Barkod</th><th>Paket</th><th>Koli</th><th>Ekim</th><th>Ocak</th><th>Şubat</th><th>Nisan</th><th>Mayıs</th><th>% Ekim→Ocak</th><th>% Ocak→Şubat</th><th>% Şubat→Nisan</th><th>% Nisan→Mayıs</th><th>% Ekim→Mayıs</th><th>Durum</th></tr></thead><tbody>'+list.map(function(r){return '<tr><td>'+esc(r.name)+'</td><td>'+esc(r.code)+'</td><td>'+esc(r.barcode)+'</td><td>'+esc(r.paket)+'</td><td>'+esc(r.koli)+'</td><td>'+money(r.Ekim)+'</td><td>'+money(r.Ocak)+'</td><td>'+money(r.Şubat)+'</td><td>'+money(r.Nisan)+'</td><td><b>'+money(r.Mayıs)+'</b></td><td class="'+trendClass(r.pct_ekim_ocak)+'">'+pct(r.pct_ekim_ocak)+'</td><td class="'+trendClass(r.pct_ocak_subat)+'">'+pct(r.pct_ocak_subat)+'</td><td class="'+trendClass(r.pct_subat_nisan)+'">'+pct(r.pct_subat_nisan)+'</td><td class="'+trendClass(r.pct_nisan_mayis)+'">'+pct(r.pct_nisan_mayis)+'</td><td class="'+trendClass(r.pct_ekim_mayis)+'">'+pct(r.pct_ekim_mayis)+'</td><td class="'+(String(r.status)==='OK'?'good':'warn')+'">'+esc(r.status)+'</td></tr>'}).join('')+'</tbody></table></div>'}
  function install(){addNav();render();var st=document.getElementById('stamp');if(st)st.textContent='Güncelleme No: '+NO}
  [0,500,1500,3000,5000].forEach(function(t){setTimeout(install,t)});window.ALALYLI_PRICE_RENDER=install;
})();