(function(){
  var NO='1137260807';
  function data(){return window.ALALYLI_PRICE_COMPARE||{rows:[]}}
  function esc(x){return String(x==null?'':x).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function n(x){return String(x||'').toLocaleLowerCase('tr-TR').replace(/ı/g,'i').replace(/İ/g,'i').replace(/\s+/g,' ').trim()}
  function money(x,d){if(x==null||x==='')return '—';var v=+x;if(!isFinite(v))return esc(x);return v.toLocaleString('tr-TR',{minimumFractionDigits:d==null?2:d,maximumFractionDigits:d==null?2:d})}
  function cls(p){if(p==null)return 'warn'; if(p>=15)return 'bad'; if(p>=5)return 'warn'; return 'good'}
  function addNav(){if(document.querySelector('[data-s="listefiyat"]'))return;var side=document.querySelector('.side');if(!side)return;var b=document.createElement('button');b.className='nav';b.dataset.s='listefiyat';b.textContent='Liste Fiyatları';b.onclick=function(){document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.s==='listefiyat'));document.querySelectorAll('.section').forEach(s=>s.classList.toggle('active',s.id==='listefiyat'));var t=document.getElementById('title');if(t)t.textContent='Liste Fiyatları'};var ref=document.querySelector('[data-s="kontrol"]');side.insertBefore(b,ref||null);var main=document.querySelector('.main');var sec=document.createElement('section');sec.id='listefiyat';sec.className='section';sec.innerHTML='<div class="card" id="priceCard"><div class="head"><h3>Ürün Liste Fiyatları Karşılaştırma</h3><div class="muted">Nisan ve Mayıs liste fiyatları yan yana. Artış oranı KDV hariç net fiyat üzerinden hesaplanır.</div></div><div style="padding:12px"><div class="mini"><div class="box"><small>Ürün Ara</small><input id="priceSearch" placeholder="Ürün, barkod, kod yaz" style="width:100%;padding:10px;border-radius:8px;border:1px solid #b8cce5;font-weight:900"></div><div class="box"><small>Filtre</small><select id="priceFilter" style="width:100%;padding:10px;border-radius:8px;font-weight:900"><option value="all">Tüm ürünler</option><option value="up15">%15 ve üstü artan</option><option value="up5">%5 ve üstü artan</option><option value="missing">Eksik listede olan</option></select></div><div class="box"><small>Kaynak</small><b id="priceSource">—</b></div><div class="box"><small>Kayıt</small><b id="priceCount">—</b></div></div><div id="priceBody"></div></div></div>';main.appendChild(sec);document.getElementById('priceSearch').oninput=render;document.getElementById('priceFilter').onchange=render}
  function render(){var D=data(),rows=D.rows||[],q=n(document.getElementById('priceSearch')&&document.getElementById('priceSearch').value),f=document.getElementById('priceFilter')&&document.getElementById('priceFilter').value||'all';var list=rows.filter(function(r){var ok=!q||n([r.name,r.barcode,r.code].join(' ')).indexOf(q)>=0;if(!ok)return false;if(f==='up15')return (r.artis_pct||0)>=15;if(f==='up5')return (r.artis_pct||0)>=5;if(f==='missing')return r.status!=='OK';return true});document.getElementById('priceSource').textContent=D.source||'—';document.getElementById('priceCount').textContent=list.length+' / '+rows.length;var body=document.getElementById('priceBody');if(!body)return;body.innerHTML='<div class="wrap" style="max-height:72vh"><table><thead><tr><th>Ürün</th><th>Kod</th><th>Barkod</th><th>Paket</th><th>Koli</th><th>Nisan Hrç</th><th>Mayıs Hrç</th><th>Artış TL</th><th>Artış %</th><th>Nisan Ped/TL</th><th>Mayıs Ped/TL</th><th>Durum</th></tr></thead><tbody>'+list.map(function(r){return '<tr><td>'+esc(r.name)+'</td><td>'+esc(r.code)+'</td><td>'+esc(r.barcode)+'</td><td>'+esc(r.paket)+'</td><td>'+esc(r.koli)+'</td><td>'+money(r.nisan_hrc)+'</td><td><b>'+money(r.mayis_hrc)+'</b></td><td>'+money(r.artis_tl)+'</td><td class="'+cls(r.artis_pct)+'">'+(r.artis_pct==null?'—':'%'+money(r.artis_pct))+'</td><td>'+money(r.nisan_ped,4)+'</td><td>'+money(r.mayis_ped,4)+'</td><td class="'+(r.status==='OK'?'good':'warn')+'">'+esc(r.status)+'</td></tr>'}).join('')+'</tbody></table></div>'}
  function install(){addNav();render();var st=document.getElementById('stamp');if(st && !/1137/.test(st.textContent)) st.textContent='Güncelleme No: '+NO}
  [0,500,1500,3000].forEach(function(t){setTimeout(install,t)});window.ALALYLI_PRICE_RENDER=install;
})();
