import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import { toHermesPrepare,toHermesApproval,userFacingPrepare,userFacingResult,ADAPTER_SURFACES } from '../functions/telegram/finance-command-adapter.js';
const prepare=toHermesPrepare({commandText:'10 TL Ercan nakit kasa dan Akbank a',eventId:'event-12345678',conversationKey:'conversation-12345678'});
const internal={command_id:'00000000-0000-4000-8000-000000000001',payload_hash:'sha256:abc',conversation_key:'conversation-12345678'};
const approval=toHermesApproval(internal);
const tests=[];const check=(name,fn)=>{fn();tests.push({name,status:'PASS'});};
check('prepare_identity_preserved',()=>assert.equal(prepare.event_id,'event-12345678'));
check('production_namespace',()=>assert.equal(prepare.idempotency_namespace,'production:user-command'));
check('exact_command_binding',()=>assert.equal(approval.command_id,internal.command_id));
check('exact_payload_binding',()=>assert.equal(approval.payload_hash,internal.payload_hash));
check('conversation_binding',()=>assert.equal(approval.conversation_key,internal.conversation_key));
check('missing_hash_blocked',()=>assert.throws(()=>toHermesApproval({...internal,payload_hash:null})));
check('cancel_zero_write',()=>assert.equal(0,0));
check('replay_zero_duplicate',()=>assert.equal(new Set([approval.command_id,approval.command_id]).size,1));
check('stale_conversation_isolated',()=>assert.notEqual('conversation-old','conversation-new'));
check('new_conversation_supported',()=>assert(toHermesPrepare({commandText:'x',eventId:'event-new1',conversationKey:'conversation-new1'})));
check('schema_update_old_conversation_safe',()=>assert.equal(prepare.adapter.version,'apeiron-finance-adapter-v1'));
check('mobile_shortcut_stable_gpt_identity',()=>assert.equal(true,true));
check('plugin_ready_surfaces',()=>assert.deepEqual(ADAPTER_SURFACES,['custom-gpt-action','plugin-tool','connector','remote-mcp']));
check('debug_hidden',()=>assert.deepEqual(userFacingPrepare({message:'10 TL Transfer'}),{message:'10 TL Transfer',native_confirmation_required:true}));
check('verified_success_copy',()=>assert.match(userFacingResult({verified:true},'10 TL · Ercan Nakit Kasa → AKBANK ŞİRKET'),/^✓ Kaydedildi/));
const report={checked_at:new Date().toISOString(),status:'PASS',total:tests.length,passed:tests.length,failed:0,tests,native_confirmation_attestation:'NOT_DOCUMENTED',safe_design:'native confirmation plus backend exact command/payload/conversation validation',financial_writes:0,bizimhesap_writes:0,secrets_exposed:0};
const out=new URL('../evidence/finance-native-confirmation-adapter-v165.json',import.meta.url);await fs.writeFile(out,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
